import React, { useState, useRef, useEffect } from 'react';
import { useBanking } from '../../context/BankingContext';
import { NorthernTrustLogo } from '../common/NorthernTrustLogo';
import { RegulatoryLogos } from '../common/RegulatoryLogos';
import {
  Building2,
  ShieldCheck,
  ShieldAlert,
  Lock,
  ArrowRight,
  Eye,
  EyeOff,
  Sliders,
  Terminal,
  ArrowLeft,
  KeyRound,
  Smartphone,
  CheckCircle2,
  AlertCircle,
  QrCode
} from 'lucide-react';
import { AdminGoogleAuthenticatorModal } from './AdminGoogleAuthenticatorModal';

export const AdminLoginView: React.FC = () => {
  const { login, navigateTo, setIsAdminMode, verifyAdminTotp } = useBanking();
  const [step, setStep] = useState<'credentials' | 'totp'>('credentials');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [department, setDepartment] = useState('Global Treasury & Wire Clearance Desk');
  const [showPassword, setShowPassword] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  // 2FA Google Authenticator state
  const [digits, setDigits] = useState<string[]>(['', '', '', '', '', '']);
  const [isPairingModalOpen, setIsPairingModalOpen] = useState(false);
  const totpInputRefs = useRef<(HTMLInputElement | null)[]>([]);

  useEffect(() => {
    if (step === 'totp') {
      setTimeout(() => totpInputRefs.current[0]?.focus(), 150);
    }
  }, [step]);

  const handleCredentialsSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMessage('');
    setIsLoading(true);

    setTimeout(() => {
      setIsLoading(false);
      if (!username || !password) {
        setErrorMessage('Please provide both administrative credentials.');
        return;
      }
      // Valid credentials move to personal Google Authenticator challenge
      setStep('totp');
    }, 350);
  };

  const handleDigitChange = (index: number, val: string) => {
    const cleanVal = val.replace(/\D/g, '').slice(-1);
    const newDigits = [...digits];
    newDigits[index] = cleanVal;
    setDigits(newDigits);
    setErrorMessage('');

    if (cleanVal && index < 5) {
      totpInputRefs.current[index + 1]?.focus();
    }
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Backspace' && !digits[index] && index > 0) {
      totpInputRefs.current[index - 1]?.focus();
    }
  };

  const handlePaste = (e: React.ClipboardEvent) => {
    e.preventDefault();
    const pasted = e.clipboardData.getData('text').replace(/\D/g, '').slice(0, 6);
    if (pasted) {
      const newDigits = [...digits];
      for (let i = 0; i < 6; i++) {
        newDigits[i] = pasted[i] || '';
      }
      setDigits(newDigits);
      const nextIndex = Math.min(pasted.length, 5);
      totpInputRefs.current[nextIndex]?.focus();
    }
  };

  const handleTotpSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const code = digits.join('');
    if (code.length !== 6) {
      setErrorMessage('Please enter all 6 digits generated by your Google Authenticator app.');
      return;
    }

    setIsLoading(true);
    setErrorMessage('');

    const isValid = await verifyAdminTotp(code);
    setIsLoading(false);

    if (isValid) {
      setIsAdminMode(true);
      navigateTo('/admin/dashboard');
    } else {
      setErrorMessage('Google Authenticator code verification failed. Ensure your app is synchronized and the 30-second token has not expired.');
    }
  };

  return (
    <div className="min-h-screen bg-[#F5F7FA] text-[#20242A] flex flex-col justify-between">
      {/* Institutional Admin Header */}
      <header className="h-16 bg-[#0B1F6A] border-b border-[#081552] px-6 sm:px-10 flex items-center justify-between shadow-xs text-white">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-white text-[#147A52] flex items-center justify-center font-bold shadow-xs p-1.5 shrink-0">
            <NorthernTrustLogo className="w-full h-full text-[#147A52]" color="#147A52" title="Northern Trust" />
          </div>
          <div className="flex flex-col justify-center">
            <div className="flex items-center gap-2">
              <span className="font-serif font-bold text-base sm:text-lg tracking-tight text-white leading-tight">
                Northern Trust
              </span>
              <span className="text-[9px] px-2 py-0.5 rounded-md bg-white/15 text-white font-mono font-bold tracking-wider border border-white/25">
                Staff Operations Desk
              </span>
            </div>
            <span className="text-[10px] sm:text-[11px] font-medium tracking-[0.14em] uppercase text-[#D8DEE8] leading-tight mt-0.5">
              Banking &amp; Institutional Operations Enclave
            </span>
          </div>
        </div>

        <div>
          <button
            type="button"
            onClick={() => navigateTo('/login')}
            className="text-xs text-[#D8DEE8] hover:text-white font-medium flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 border border-white/20 transition-all cursor-pointer"
          >
            <ArrowLeft className="w-3.5 h-3.5 text-[#D8DEE8]" />
            <span>Client Banking Portal</span>
          </button>
        </div>
      </header>

      {/* Main Admin Login Form */}
      <main className="flex-1 flex items-center justify-center p-4 sm:p-6">
        <div className="w-full max-w-md">
          <div className="bg-white rounded-lg border border-[#D8DEE8] p-7 sm:p-8 shadow-sm">
            {step === 'credentials' ? (
              <>
                {/* Initial Company Brand Logo and Name */}
                <div className="flex items-center gap-3.5 mb-6 pb-4 border-b border-[#D8DEE8]">
                  <div className="w-12 h-12 rounded-xl bg-[#147A52] text-white flex items-center justify-center p-2 shrink-0 shadow-sm">
                    <NorthernTrustLogo className="w-full h-full text-white" color="#FFFFFF" title="Northern Trust" />
                  </div>
                  <div>
                    <span className="font-serif font-black text-2xl text-[#20242A] block leading-tight tracking-tight">
                      Northern Trust
                    </span>
                    <span className="text-[11px] font-mono font-bold tracking-wider uppercase text-[#147A52] block mt-0.5">
                      Bank Operations &amp; Clearance Enclave
                    </span>
                  </div>
                </div>

                {/* Header info */}
                <div className="mb-6">
                  <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-md text-[11px] font-semibold mb-2 bg-[#147A52]/10 text-[#147A52] border border-[#147A52]/20">
                    <ShieldCheck className="w-3.5 h-3.5 text-[#147A52]" /> Bank Institutional Gateway
                  </div>
                  <h1 className="text-xl font-bold tracking-tight text-[#20242A]">
                    Operations &amp; Compliance Sign In
                  </h1>
                  <p className="text-xs text-[#5F6670] mt-1 leading-relaxed">
                    Authorized access only for Treasury Officers, AML Compliance Auditors, and Operations Staff.
                  </p>
                </div>

                {/* Error Message */}
                {errorMessage && (
                  <div className="mb-5 p-3 rounded bg-red-50 border border-red-200 text-[#B42318] text-xs font-semibold flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 shrink-0" />
                    <span>{errorMessage}</span>
                  </div>
                )}

                {/* Staff Credentials Form */}
                <form onSubmit={handleCredentialsSubmit} className="space-y-4">
                  <div>
                    <label className="block text-xs font-bold text-[#20242A] mb-1.5">
                      Staff Employee ID / Admin Username
                    </label>
                    <input
                      type="text"
                      required
                      value={username}
                      onChange={(e) => setUsername(e.target.value)}
                      placeholder="Staff Employee ID or Username"
                      className="form-input font-mono"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-[#20242A] mb-1.5">
                      Security Token / Master Password
                    </label>
                    <div className="password-wrapper">
                      <input
                        type={showPassword ? 'text' : 'password'}
                        required
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        placeholder="Enter security password"
                        className="form-input font-mono"
                      />
                      <button
                        type="button"
                        onClick={() => setShowPassword(!showPassword)}
                        className="password-toggle"
                        aria-label={showPassword ? 'Hide password' : 'Show password'}
                      >
                        {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4 text-[#15803d]" />}
                      </button>
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-[#20242A] mb-1.5">
                      Department / Terminal Assignment
                    </label>
                    <select
                      value={department}
                      onChange={(e) => setDepartment(e.target.value)}
                      className="form-input text-xs"
                    >
                      <option value="Global Treasury & Wire Clearance Desk">Global Treasury &amp; Wire Clearance Desk</option>
                      <option value="AML / KYC Surveillance Unit">AML / KYC Surveillance Unit</option>
                      <option value="Institutional Forensics & SIEM Desk">Institutional Forensics &amp; SIEM Desk</option>
                      <option value="Executive Supervisory Terminal">Executive Supervisory Terminal</option>
                    </select>
                  </div>

                  <div className="p-3 rounded bg-[#F5F7FA] border border-[#D8DEE8] text-[11px] text-[#5F6670] space-y-1 font-mono">
                    <div className="flex items-center justify-between">
                      <span>Workstation IP:</span>
                      <span className="text-[#20242A] font-semibold">192.168.1.100 (HQ Enclave)</span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span>Authentication:</span>
                      <span className="text-[#147A52] font-semibold">Google Authenticator (RFC 6238)</span>
                    </div>
                  </div>

                  <button
                    type="submit"
                    disabled={isLoading}
                    className="w-full h-11 rounded-lg bg-[#101F7A] hover:bg-[#081552] text-white font-semibold text-xs flex items-center justify-center gap-2 transition-colors cursor-pointer shadow-xs disabled:opacity-60"
                  >
                    {isLoading ? (
                      <div className="w-4 h-4 border-2 border-white/40 border-t-white rounded-full animate-spin" />
                    ) : (
                      <>
                        <KeyRound className="w-4 h-4" />
                        <span>Continue to Authenticator Verification</span>
                        <ArrowRight className="w-4 h-4" />
                      </>
                    )}
                  </button>
                </form>
              </>
            ) : (
              /* Step 2: Google Authenticator Verification */
              <>
                <div className="mb-6 pb-4 border-b border-[#D8DEE8] text-center">
                  <div className="w-12 h-12 rounded-lg bg-[#0B1F6A]/10 text-[#0B1F6A] flex items-center justify-center mx-auto mb-3 shadow-2xs">
                    <Smartphone className="w-6 h-6 text-[#0B1F6A]" />
                  </div>
                  <h1 className="text-xl font-bold tracking-tight text-[#0B1F6A]">
                    Google Authenticator
                  </h1>
                  <p className="text-xs text-[#5F6670] mt-1.5 leading-relaxed">
                    Enter the 6-digit dynamic passcode from your personal Google Authenticator app for <strong className="text-[#20242A]">{username}</strong>.
                  </p>
                </div>

                {/* Error Message */}
                {errorMessage && (
                  <div className="mb-5 p-3 rounded bg-red-50 border border-red-200 text-[#B42318] text-xs font-semibold flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 shrink-0" />
                    <span>{errorMessage}</span>
                  </div>
                )}

                <form onSubmit={handleTotpSubmit} className="space-y-5">
                  <div className="space-y-2">
                    <label className="block text-xs font-bold text-center text-[#20242A]">
                      6-Digit Dynamic Passcode
                    </label>
                    <div className="flex justify-center gap-2" onPaste={handlePaste}>
                      {digits.map((digit, idx) => (
                        <input
                          key={idx}
                          ref={(el) => { totpInputRefs.current[idx] = el; }}
                          type="text"
                          inputMode="numeric"
                          pattern="[0-9]*"
                          maxLength={1}
                          value={digit}
                          onChange={(e) => handleDigitChange(idx, e.target.value)}
                          onKeyDown={(e) => handleKeyDown(idx, e)}
                          className="w-11 h-13 sm:w-12 sm:h-14 text-center text-xl font-bold font-mono border-2 border-gray-300 rounded-md focus:border-[#147A52] focus:ring-2 focus:ring-[#147A52]/20 focus:outline-none transition-all"
                          autoFocus={idx === 0}
                        />
                      ))}
                    </div>
                  </div>

                  <button
                    type="submit"
                    disabled={isLoading || digits.join('').length !== 6}
                    className={`w-full h-11 rounded-lg font-semibold text-xs flex items-center justify-center gap-2 transition-colors ${
                      digits.join('').length === 6 && !isLoading
                        ? 'bg-[#101F7A] hover:bg-[#081552] text-white shadow-xs cursor-pointer'
                        : 'bg-gray-100 text-gray-400 cursor-not-allowed border border-gray-200'
                    }`}
                  >
                    {isLoading ? (
                      <div className="w-4 h-4 border-2 border-white/40 border-t-white rounded-full animate-spin" />
                    ) : (
                      <>
                        <ShieldCheck className="w-4 h-4" />
                        <span>Verify &amp; Enter Operations Console</span>
                      </>
                    )}
                  </button>

                  <div className="flex items-center justify-between pt-2 text-xs">
                    <button
                      type="button"
                      onClick={() => { setStep('credentials'); setErrorMessage(''); }}
                      className="text-[#5F6670] hover:text-[#0B1F6A] flex items-center gap-1 cursor-pointer"
                    >
                      <ArrowLeft className="w-3.5 h-3.5" /> Back to credentials
                    </button>
                    <button
                      type="button"
                      onClick={() => setIsPairingModalOpen(true)}
                      className="text-[#0B1F6A] hover:underline font-semibold flex items-center gap-1 cursor-pointer"
                    >
                      <QrCode className="w-3.5 h-3.5" /> Pair / View QR
                    </button>
                  </div>
                </form>
              </>
            )}

            {/* Audit compliance notice */}
            <div className="mt-5 p-3 rounded-lg bg-[#F5F7FA] border border-[#D8DEE8] text-[11px] text-[#5F6670] leading-relaxed">
              <span className="font-bold text-[#20242A] block mb-0.5">Immutable Audit Notice</span>
              All administrative access, ledger modifications, customer record lookups, and wire approvals are logged into the regulatory SIEM forensic vault pursuant to 12 CFR Part 21.
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="py-3.5 bg-[#0B1F6A] border-t border-[#081552] px-4 sm:px-6 flex flex-col md:flex-row items-center justify-between gap-3 text-xs text-[#D8DEE8]">
        <div>Northern Trust Company • Regulatory Compliance Division</div>
        <RegulatoryLogos variant="navy-footer" showDetails={false} />
      </footer>

      {/* Google Authenticator Pairing Modal */}
      <AdminGoogleAuthenticatorModal
        isOpen={isPairingModalOpen}
        onClose={() => setIsPairingModalOpen(false)}
      />
    </div>
  );
};
